src := $(obj)

__build :

target :=

build := -f $(srctree)/Makefile.build obj

include $(src)/Makefile

include $(srctree)/Makefile.lib

__build : $(subdirs) target
	echo what???

$(subdirs) : FORCE
	echo $(MAKELEVEL)
	echo in Makefile.build $(srctree)
	echo in Makefile.build $(src)
	@echo subdirs -- $(subdirs)
	$(Q)$(MAKE) $(build)=$@

FORCE :

.PHONY: __build $(subdirs) FORCE
